image: node:8-alpine

# Cache node modules - speeds up future builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules


stages:
  - compile
  - test
  - build
  - deploy

# ------------------------------ compile stage ------------------------------
compile:
  stage: compile
  script:
    - npm install

# ------------------------------ test stage ------------------------------
test:
  stage: test
  script:
    - npm test
    ### ToDo: selvitä ajaako Gitlab automaattisesti Jestiä CI-moodissa (ts. ei interaktiivisesti)
    ### vai pitäisikö asettaa käsin Jestille optio --ci (tai --watchAll=false), esim. npm test -- --ci

# ------------------------------ build stage ------------------------------
.build_dev:
  stage: build
  script:
    - npm run build
  artifacts:
    name: lataamo-build
    paths:
      - build

.build_test:
  stage: build
  script:
    - npm run build
  artifacts:
    name: lataamo-build
    paths:
      - build

build_prod:
  stage: build
  script:
    - npm run build
  artifacts:
    name: lataamo-build
    paths:
      - build

# ------------------------------ deploy stage ------------------------------

.deploy_script:
  script:
    - echo "====== Install rsync and openssh ========="
    - apk add --no-cache rsync openssh
    - echo "====== Activate the ssh-agent ========"
    - eval $(ssh-agent -s)
    - echo "======= Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store ====="
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "====== Add target servers secret key ======"
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY  >> ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "====== Test ssh connection and make react-app folder if not exist ======"
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T lataamo@$SERVER "mkdir -p /home/lataamo/react-app"
    - echo "====== Sync local and remote directory ======"
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -azPq -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --delete ./build/ lataamo@$SERVER:/home/lataamo/react-app


# Define the process for deploy stage to development environment
deploy_dev:
  stage: deploy
  environment:
    name: development
    url: https://$LATAAMO_DEV:8000
  #only:
  #  - master
  variables:
    SERVER: $LATAAMO_DEV
  before_script:
    - echo "====== Deploy to development server ========"
  extends: .deploy_script

# Define the process for deploy stage to test environment
deploy_test:
  stage: deploy
  environment:
    name: test
    url: https://$LATAAMO_TEST:8000
  only:
    - test
  variables:
    SERVER: $LATAAMO_TEST
  before_script:
    - echo "====== Deploy to test server ========"
  extends: .deploy_script

# Define the process for deploy stage to prod environment
deploy_prod:
  stage: deploy
  environment:
    name: production
    url: https://$LATAAMO_PROD
  only:
    - prod
  when: manual
  variables:
    SERVER: $LATAAMO_PROD
  before_script:
    - echo "====== Deploy to production server ========"
  extends: .deploy_script
