image: node:8-alpine

before_script:
  - npm install

# Cache node modules - speeds up future builds
cache:
  paths:
    - node_modules

# Define the stages
stages:
  - test
  - build

# Define the process for each stage
test:
  stage: test
  script:
    - npm test

# Define the process for each stage
build:
  stage: build
  script:
    - npm run build

