
const ROLE_ANONYMOUS = 'ROLE_ANONYMOUS';
const ROLE_KATSOMO = 'ROLE_KATSOMO';

const MOODLE_ACL_INSTRUCTOR = '_Instructor';
const MOODLE_ACL_LEARNER = '_Learner';
const STATUS_PUBLISHED = 'status_published';
const STATUS_MOODLE = 'status_moodle';
const STATUS_PRIVATE = 'status_private';

const VIDEO_PROCESSING_RUNNING = 'RUNNING';
const VIDEO_PROCESSING_FAILED = 'FAILED';
const VIDEO_PROCESSING_INSTANTIATED = 'INSTANTIATED';


module.exports = {
    ROLE_ANONYMOUS,
    ROLE_KATSOMO,
    STATUS_PUBLISHED,
    STATUS_PRIVATE,
    STATUS_MOODLE,
    MOODLE_ACL_INSTRUCTOR,
    MOODLE_ACL_LEARNER,
    VIDEO_PROCESSING_FAILED,
    VIDEO_PROCESSING_RUNNING,
    VIDEO_PROCESSING_INSTANTIATED
};